# Numpy Part II

In [13]:
import numpy as np
# placeholder arrays
a_zero = np.zeros((5,5))
a_one = np.ones((5,5))
# sometimes used in linear algebra settings
a_eye = np.eye(5,5, k=1)
# fills with not quite 0 but may be faster than np.zeros
a_empty = np.empty((25,25))

In [16]:
a_empty

array([[ 1.49166815e-154,  1.49166815e-154,  4.24399158e-314,
         0.00000000e+000,  4.94065646e-324,  2.36967697e-314,
         2.24512704e-314,  2.48884589e-242,  2.36971249e-314,
         2.24628000e-314, -1.04982965e+289,  2.36967302e-314,
         2.24629123e-314, -1.37082239e+240,  2.36971018e-314,
         2.24571162e-314, -3.66091535e+109,  2.36971271e-314,
         2.24636849e-314,  9.66068011e-129,  2.36967290e-314,
         2.24639382e-314,  1.61640563e-035,  2.36967320e-314,
         2.24630441e-314],
       [-4.85930056e-241,  2.36967326e-314,  2.24617620e-314,
        -1.70096790e-015,  2.36967332e-314,  2.24617623e-314,
         5.25802791e-058,  2.36967338e-314,  2.24634429e-314,
        -2.02482517e-227,  2.36967314e-314,  2.24640440e-314,
        -1.22378357e-224,  2.36971612e-314,  2.24503670e-314,
         1.86067767e-191,  2.36971618e-314,  2.24640479e-314,
        -1.33591640e+141,  2.36971275e-314,  2.24641120e-314,
         8.22191286e-143,  2.36971280e-314,

In [15]:
# create array an array of equally spaced values
a = np.linspace(-4,4, 40)
a

array([-4.        , -3.79487179, -3.58974359, -3.38461538, -3.17948718,
       -2.97435897, -2.76923077, -2.56410256, -2.35897436, -2.15384615,
       -1.94871795, -1.74358974, -1.53846154, -1.33333333, -1.12820513,
       -0.92307692, -0.71794872, -0.51282051, -0.30769231, -0.1025641 ,
        0.1025641 ,  0.30769231,  0.51282051,  0.71794872,  0.92307692,
        1.12820513,  1.33333333,  1.53846154,  1.74358974,  1.94871795,
        2.15384615,  2.35897436,  2.56410256,  2.76923077,  2.97435897,
        3.17948718,  3.38461538,  3.58974359,  3.79487179,  4.        ])

In [18]:
# mathematical operations
a = np.arange(15).reshape(3,5)
a ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [19]:
b = np.arange(15).reshape(3,5)
a - b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
a[1,2] = 1
b == a

array([[ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [26]:
# summarizing
a.sum()
a.mean()
a.max()
a.std()
a[:,0].sum()

15

In [1]:
# numpy random module
import numpy.random as npr
npr.standard_normal((3,5))

array([[-0.77791525, -0.50384271, -0.84346963,  0.25957839, -0.69208201],
       [-1.09528802, -1.47706467, -0.50203208, -0.18265032, -0.93032448],
       [-0.55516896, -0.25171456, -0.15358476, -0.74549308,  0.44731835]])

In [27]:
# choosing every n-th value
y = npr.standard_normal(500)
y[:25]

array([-0.34406869, -2.11861992,  0.50922844,  0.49979826,  0.55343382,
       -0.30115707, -2.05583425,  0.08216065, -0.81989427, -1.61331867,
       -2.18545485,  0.52326697, -1.00651371,  0.10747144, -1.43210796,
       -0.83121712, -1.23483714,  1.63510331,  0.08101711, -0.56546902,
        1.54012494, -0.31180942,  0.47238518,  0.65860495,  0.39945212])

In [30]:
y[::12]

array([-0.34406869, -1.00651371,  0.39945212, -1.51150589,  0.82736375,
        0.95110086, -1.18463948,  0.54732842,  1.34398784, -0.92463433,
        0.09182256, -0.82639692,  1.78521239,  2.05082033,  0.36425268,
       -1.18394711, -0.67003169,  1.11419382, -0.20240618, -0.43171695,
        0.59156861,  0.27458975,  0.83795142,  1.1398382 , -0.26385051,
       -0.98807564,  0.20221938, -0.02859606,  0.16298716,  0.03759667,
       -1.35071613, -0.91247145,  0.14142708, -1.76202122,  0.585469  ,
        1.09717508, -0.83970149,  0.17139393, -0.46445265, -1.60114762,
        1.27814437,  0.41128325])